In [187]:
import numpy as np
import matplotlib.pyplot as plt

# list转ndarray

In [188]:
# list转ndarray
my_list = list(range(1, 11))
print(my_list)
print(type(my_list))

my_ndarray = np.array(my_list)
print(my_ndarray)
print(type(my_ndarray))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'list'>
[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


# list与ndarray的运算效率对比

In [189]:
import random
import time

a = []
for i in range(10 ** 7):
    a.append(random.random())
print("随机生成10^7个随机数的列表")

b = np.array(a)
print("转换为ndarray")

t1 = time.time()
sum_list = np.sum(a)
t2 = time.time()

t3 = time.time()
sum_ndarray = np.sum(b)
t4 = time.time()

# ndarray的计算效率优于python的list
print(f"list求和耗时：{t2 - t1}秒, ndarray求和耗时：{t4 - t3}秒")

随机生成10^7个随机数的列表
转换为ndarray
list求和耗时：0.33391380310058594秒, ndarray求和耗时：0.009996891021728516秒


# ndarray的基本操作 

In [190]:
# 创建ndarray
t1 = np.array([1, 2, 3])
print(t1)
print(type(t1))

[1 2 3]
<class 'numpy.ndarray'>


In [191]:
# range转ndarray
print(type(range(10)))  # range返回的是一个range对象，不能直接转换为ndarray
t2 = np.array(range(10))
print(t2)
print(type(t2))

<class 'range'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [192]:
# arange
t3 = np.arange(0, 10, 2)  # 等价于range(0,10,2),返回ndarray
print(t3)
print(type(t3))  # 

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [193]:
# 二维列表转ndarray
list2 = [[1, 2], [3, 4], [5, 6]]
twoArray = np.array(list2)
print(type(twoArray))
print(twoArray)  # ndarray的输出是没有逗号的
print(list2)  #列表的输出是有逗号的

<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]
[[1, 2], [3, 4], [5, 6]]


In [194]:
# ndarray转换为列表
twoArray.tolist()
print(list2)

[[1, 2], [3, 4], [5, 6]]


# ndarray的常用属性

In [195]:
list2 = [[1, 2], [3, 4], [5, 6]]
twoArray = np.array(list2)

# ndim属性，维度
print(twoArray.ndim)

#  shape属性，形状（行，列） (0 axis,1 axis)
print(twoArray.shape)

# size属性，元素个数
print(twoArray.size)

# dtype属性，数据类型
print(twoArray.dtype)  #默认int32,4个字节，数据范围 -21亿到21亿(?)

2
(3, 2)
6
int64


# 调整数组形状

In [196]:
four = np.array([[1, 2, 3], [4, 5, 6]])
print(four)

# 对数组的修改是在原数组上进行的
four1 = four
print(id(four))
print(id(four1))

four.shape = (3, 2)  # 改变形状
print(id(four))  # 地址没有发生变化
print(id(four1))  # 地址没有发生变化
print(four)

[[1 2 3]
 [4 5 6]]
2004378166512
2004378166512
2004378166512
2004378166512
[[1 2]
 [3 4]
 [5 6]]


In [197]:
# 返回一个新的数组，reshape后id和之前的不一样
four2 = four.reshape(2, 3)
print(four)
print(id(four))
print(id(four2))
print(four2)

[[1 2]
 [3 4]
 [5 6]]
2004378166512
2004666451984
[[1 2 3]
 [4 5 6]]


In [198]:
# 将多维变成一维数组
# 默认情况下‘C’以行为主的顺序展开，‘F’（Fortran风格）意味着以列的顺序展开
print(four)
five = four.reshape((6,), order='C')  # 元组必须加逗号
six = four.flatten()  # flatten()返回一个一维数组
print(five)
print('-' * 50)
print(six)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
--------------------------------------------------
[1 2 3 4 5 6]


In [199]:
seven = five.reshape(3, 2)  # 改变形状
print(seven)

[[1 2]
 [3 4]
 [5 6]]


In [200]:
# 拓展：数组的形状
t = np.arange(24)  #和列表的range函数一样，生成一个数组
print(t)
print(f'shape{t.shape}')
print(t.ndim)
# 转换成二维
t1 = t.reshape((4, 6))
print(t1)
print(t1.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
shape(24,)
1
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


In [201]:
# 转成三维
#最前面的是零轴，轴越小，越靠外，最小的轴是最外层
# 0轴，1轴，2轴
t2 = t.reshape((2, 3, 4))
print(t2)
print(t2.shape)
print(t2.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
3


In [202]:
# 转成四维
t3 = t.reshape((2, 3, 2, 2))
print(t3)
print(t3.shape)
print(t3.ndim)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]
(2, 3, 2, 2)
4


In [203]:
#将数组转换为列表 tolist
a = np.array([9, 12, 88, 14, 25])
print(type(a))
list_a = a.tolist()  # tolist()方法将数组转换为列表
print(list_a)
print(type(list_a))


<class 'numpy.ndarray'>
[9, 12, 88, 14, 25]
<class 'list'>


# numpy的数据类型

In [204]:
f = np.array([1, 2, 3, 4, 127], dtype=np.int8)  # dtype参数指定数据类型 int8 1个字节
print(f.itemsize)  #  itemsize属性获取数据类型占用字节数
print(f.dtype)  # 获取数据类型

1
int8


In [205]:
# 溢出，超出数据类型范围
f[4] = f[4] + 1  # int8 范围是-128到127
print(f[4])

-128


C:\Users\klklklk\AppData\Local\Temp\ipykernel_48536\3134143905.py:2: RuntimeWarning: overflow encountered in scalar add
  f[4] = f[4] + 1  # int8 范围是-128到127


In [206]:
# 调整数据类型
f1 = f.astype(np.int64)  # astype()方法可以调整数据类型
print(f1.dtype)
print(f1.itemsize)  #显示字节数

int64
8


In [207]:
# 拓展随机生成小数
import random

# 使用python语法，保留两位
print(round(random.random(), 2))  # round()函数可以保留小数
# np.float16 半精度 2个字节
arr = np.array([random.random() for i in range(10)])
print(arr)
print(arr.itemsize)
print(arr.dtype)
# 取小数点后两位
print(np.round(arr, 2))

0.54
[0.54398535 0.54851987 0.79566462 0.13828196 0.15595342 0.25556789
 0.86357695 0.20840382 0.92889151 0.39712841]
8
float64
[0.54 0.55 0.8  0.14 0.16 0.26 0.86 0.21 0.93 0.4 ]


# 数组和数的运算

In [208]:
# 由于numpy的广播机机制在运算过程中，加减乘除的值被广播到所有的元素上面
t1 = np.arange(24).reshape((6, 4))
print(t1)

print("-" * 20)

t2 = t1.tolist()
print(t1 + 2)  # 对t1每一个元素加2
# print(t2+2) 不能对列表进行直接加整数操作

print("-" * 20)

print(t1 * 2)  # 对t1每一个元素乘2

print("-" * 20)

print(t1 / 2)  # 对t1每一个元素除2
#无论多少维的ndarray都可以直接和一个常数进行运算

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
--------------------
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


# ndarray与ndarray的运算

In [209]:
#形状相同,才可以进行加减乘除
t1 = np.arange(24).reshape((6, 4))
t2 = np.arange(100, 124).reshape((6, 4))
print(t1)
print(t2)
print('-' * 50)
print(t1 + t2)
print('-' * 50)
print(t1 * t2)  #是否是矩阵乘法？不是

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
--------------------------------------------------
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
--------------------------------------------------
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


In [210]:
# #shape不同，不能进行运算
# t1 = np.arange(24).reshape((4, 6))
# t2 = np.arange(6).reshape((3, 6))
# print(t1)
# print(t2)
# print(t1 - t2)

In [211]:
#一维数组和二维数组进行运算时，一维的元素个数和列数相等
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(6).reshape((1, 6))
print(t2.shape)
print(t1)
print(t2)
print(t1 + t2)  # NumPy 会自动将其扩展到与 t1 相同的形状，即4x6

(1, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0 1 2 3 4 5]]
[[ 0  2  4  6  8 10]
 [ 6  8 10 12 14 16]
 [12 14 16 18 20 22]
 [18 20 22 24 26 28]]


In [212]:
# t1 = np.arange(24).reshape((4, 6))
# t2 = np.arange(6).reshape((1, 5))
# print(t1 - t2)  # 列数不同，不能进行运算

In [213]:
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(4).reshape((4, 1))
print(t2)
print(t1)
print(t1 - t2)
(t1 - t2).shape

[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 5  6  7  8  9 10]
 [10 11 12 13 14 15]
 [15 16 17 18 19 20]]


(4, 6)

# 轴的练习

In [214]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])  # （2，3）
print(a)
print("-" * 20)
print(np.sum(a, axis=0))  # [5 7 9]，按哪个轴求和，哪个轴没了 （3，） 把轴0的元素相加
print("-" * 20)
print(np.sum(a, axis=1))  # [ 6 15]，按哪个轴求和，哪个轴没了 （2，） 把轴1的元素相加
print("-" * 20)
print(np.sum(a))  # 21，没有指定轴，所有元素相加
print("-" * 20)

[[1 2 3]
 [4 5 6]]
--------------------
[5 7 9]
--------------------
[ 6 15]
--------------------
21
--------------------


In [215]:
a = np.arange(24).reshape((2, 3, 4))
b = np.sum(a, axis=0)  # 按0轴求和，（3，4）
print("-" * 20)
print(b.shape)
c = np.sum(a, axis=1)  # 按1轴求和，（2，4）
print("-" * 20)
print(c.shape)
d = np.sum(a, axis=2)  # 按2轴求和，（2，3）
print("-" * 20)
print(d.shape)

--------------------
(3, 4)
--------------------
(2, 4)
--------------------
(2, 3)


# 索引和切片

In [216]:
import numpy as np

# 一维数组的索引和切片
a = np.arange(10)
print(a)

print(a[0])  # 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素

print(a[2:])  # 如果为 [2:]，表示从该索引开始以后的所有项都将被提取

print(a[2:8:2])  #切片是左闭右开 从索引 2 开始到索引 7 停止，间隔为 2

[0 1 2 3 4 5 6 7 8 9]
0
[2 3 4 5 6 7 8 9]
[2 4 6]


In [217]:
import numpy as np

# 二维数组的索引和切片
t1 = np.arange(24).reshape(4, 6)
print(t1)
print('*' * 20)
print(t1[1])  # 取一行(一行代表是一条数据，索引也是从0开始的) print(t1[1,:]) # 取一行
print('*' * 20)
print(t1[1:])  # 取连续的多行
print('*' * 20)
print(t1[1:3, :])  # 取连续的多行 
"""
1:3：表示选择从第 2 行（索引 1）到第 3 行（索引 2），不包括索引 3。所以它取的是第 2 行和第 3 行。
:：表示取所有列
"""
print('*' * 20)
print(t1[[0, 2, 3]])  # 取不连续的多行

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 6  7  8  9 10 11]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [218]:
# # 列表不支持索引
# t2 = np.arange(24).reshape(4, 6).tolist()
# t2[[0, 2, 3]]

In [219]:
print(t1[:, 1])  # 取一列
print('*' * 20)
print(t1[:, 1:])  # 连续的多列
print('*' * 20)
print(t1[:, [0, 2, 3]])  # 取不连续的多列
print('*' * 20)
print(t1[2, 3])  # # 取某一个值,三行四列  py是t1[2][3]
print('*' * 20)
print(t1[[0, 1, 1], [0, 1, 3]])  # 取多个不连续的值，[[行，行。。。],[列，列。。。]]
print('*' * 20)
print(t1[1:3, 1:4])  #取1-3行，1-4列

[ 1  7 13 19]
********************
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
********************
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
********************
15
********************
[0 7 9]
********************
[[ 7  8  9]
 [13 14 15]]


# 修改数组元素

In [220]:
import numpy as np

t = np.arange(24).reshape(4, 6)
print(t)
print(id(t))
print('-' * 50)
# # 修改某一行的值
#t[1,:]=0
#
# # 修改某一列的值
# t[:,1]=0
#
# # 修改连续多行
# t[1:3,:]=0
#
# # 修改连续多列
# t[:,1:4]=0
#
# # 修改多行多列，取第二行到第四行，第三列到第五列
# t[1:3,2:5]=0
#
# # 修改多个不相邻的点
# t[[0,1],[1,3]]=0

# 可以根据条件修改，比如讲小于10的值改掉
# t[t<10]=0

# 使用逻辑判断
# np.logical_and	& # np.logical_or	|
# np.logical_not		~
# t[(t>2)&(t<6)]=0	# 逻辑与，and
# t[(t<2)|(t>6)]=0	# 逻辑或，or
# t[~(t>6)]=0	# 逻辑非
# print(t)
# t = t.clip(10, 18)
print(id(t))
print(t)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
2004377950832
--------------------------------------------------
2004377950832
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [221]:
# 返回布尔型数组
t = np.arange(24).reshape(4, 6)
print(t < 10)

[[ True  True  True  True  True  True]
 [ True  True  True  True False False]
 [False False False False False False]
 [False False False False False False]]


In [222]:
#python的三目运算
a = 10
b = 15
c = a if a > b else b
c

15

In [223]:
# # 拓 展
# # 三目运算（ np.where(condition, x, y)满足条件(condition)，输出x，不满足输出y。)）
score = np.array([[80, 88], [82, 81], [75, 81]])
print(score)
result = np.where(score < 80, True, False)  #类似于if else
print(result)
score[result] = 100  # 给满足条件的元素赋值
score

[[80 88]
 [82 81]
 [75 81]]
[[False False]
 [False False]
 [ True False]]


array([[ 80,  88],
       [ 82,  81],
       [100,  81]])

# 数据的添加，删除，去重

In [224]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])

print('第一个数组：')
print(a)
print('\n')

print(' 向数组添加元素：')
print(np.append(a, [7, 8, 9]))  #ndarray会被展平
print('\n')
print(a)
print('-' * 50)

第一个数组：
[[1 2 3]
 [4 5 6]]


 向数组添加元素：
[1 2 3 4 5 6 7 8 9]


[[1 2 3]
 [4 5 6]]
--------------------------------------------------


In [225]:
b = np.array([[7, 8, 9]])
print(b.ndim)
print(b)

2
[[7 8 9]]


In [226]:
# 延轴拼接
print('沿轴 0 添加元素：')  #往哪个轴添加，那个轴size就变大
print(np.append(a, [[7, 8, 9]], axis=0))
print('\n')
print(a)
print('沿轴 1 添加元素：')
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))
print(a)
print('-' * 50)
"""
参 数 说 明：
arr：输入数组，表示要在此数组的基础上添加元素
values：要向 arr 添加的值，需要和 arr 的形状相同，除了要添加的轴（例如，添加到行方向时，列数必须一致；添加到列方向时，行数必须一致）
axis：默认为 None。当 axis 未定义时，表示横向添加（即结果会变成一维数组）。如果 axis 定义为 0，则表示按行添加元素；如果 axis 定义为 1，则表示按列添加元素。
    - 当 axis=0 时，values 中的元素会作为新行添加到 arr 的底部，要求 values 的列数与 arr 的列数相同。
    - 当 axis=1 时，values 中的元素会作为新列添加到 arr 的右侧，要求 values 的行数与 arr 的行数相同。
"""

沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 2 3]
 [4 5 6]]
沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]
[[1 2 3]
 [4 5 6]]
--------------------------------------------------


In [227]:
# 插入元素
a = np.array([[1, 2], [3, 4], [5, 6]])

print('第一个数组：')
print(a)
print('\n')

print('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print(np.insert(a, 1, [11, 22]))
print('-' * 50)
print(np.insert(a, 1, [11, 12], axis=0))  #那个轴插入，哪个轴size变大
# print('传递了 Axis 参数。 会广播值数组来配输入数组。')

print('沿轴  0 广播：')
print(np.insert(a, 1, 11, axis=0))
print('\n')

print('沿轴  1 广播：')
print(np.insert(a, 1, [1, 2, 5], axis=1))
"""
numpy.insert
函数在给定索引之前，沿给定轴在输入数组中插入值。如果值的类型转换为要插入的数组，则它与输入数组不同。
插入操作没有原地修改（in-place），该函数会返回一个新数组。此外，如果未提供轴（axis），则输入数组会被展平（即转换为一维数组）。
"""

第一个数组：
[[1 2]
 [3 4]
 [5 6]]


未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 1 11 22  2  3  4  5  6]
--------------------------------------------------
[[ 1  2]
 [11 12]
 [ 3  4]
 [ 5  6]]
沿轴  0 广播：
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


沿轴  1 广播：
[[1 1 2]
 [3 2 4]
 [5 5 6]]


In [ ]:
# numpy.delete 函数返回从输入数组中删除指定子数组的新数组。 与 insert() 函数的情况一样，
# 如果未提供轴参数， 则输入数组将展开。
import numpy as np

a = np.arange(12).reshape(3, 4)

print('第一个数组：')
print(a)
print('\n')

print('未传递 Axis 参数。 在删除之前输入数组会被展开。')
print(np.delete(a, 5))
print('\n')
print(a)
print('删除第一行：')
print(np.delete(a, 1, axis=0))
print('\n')

print('删除第一列：')
print(np.delete(a, 1, axis=1))
'''
参 数 说 明 ： 
arr： 输 入 数 组
obj：可以被切片，整数或者整数数组，表明要从输入数组删除的子数组axis：
沿着它删除给定子数组的轴，如果未提供，则输入数组会被展开
'''

In [228]:
# numpy.unique 函数用于去除数组中的重复元素
import numpy as np

a = np.array([5, 2, 6, 2, 7, 5, 6, 9, 8, 2])

print('第一个数组：')
print(a)
print('\n')

#去除重复元素，输出的是有序序列
# print ('第一个数组的去重值：')
# u = np.unique(a)
# print (u)
# print ('\n')

# print ('去重数组的索引数组：')
# u,indices = np.unique(a, return_index = True)
# print(u)
# print (indices)
# print ('\n')

# print ('我们可以看到每个和原数组下标对应的数值：')
# print ('去重数组的下标：')
# u,indices = np.unique(a,return_inverse = True)
# print (u)
# print (indices)
# print ('\n')

print('返回去重元素的重复数量：')
u, indices = np.unique(a, return_counts=True)
print(u)
print(indices)
u

'''
arr：输入数组，如果不是一维数组则会展平
return_index：如果为true，返回新列表元素在旧列表中的位置（下标），并以列表形式储
return_inverse：如果为true，返回旧列表元素在新列表中的位置（下标），并以列表形式储
return_counts：如果为true，返回去重数组中的元素在原数组中的出现次数
'''

第一个数组：
[5 2 6 2 7 5 6 9 8 2]


返回去重元素的重复数量：
[2 5 6 7 8 9]
[3 2 2 1 1 1]


'\narr：输入数组，如果不是一维数组则会展平\nreturn_index：如果为true，返回新列表元素在旧列表中的位置（下标），并以列表形式储\nreturn_inverse：如果为true，返回旧列表元素在新列表中的位置（下标），并以列表形式储\nreturn_counts：如果为true，返回去重数组中的元素在原数组中的出现次数\n'

# numpy 数学计算

In [232]:
import numpy as np

score = np.array([[80, 88], [82, 81], [75, 81]])
print(score)

# 1. 获取所有数据最大值
print("np.max()获取 score 数组中的所有数据最大值：")
result = np.max(score)
print(result)
# 2. 获取某一个轴上的数据最大值，对应的轴就消失
print("axis 获取 score 数组中一列的最大值：")
result = np.max(score, axis=1)
print(result)
# 3. 获取最小值
print("np.min()获取 score 数组中的所有数据最小值：")
result = np.min(score)
print(result)
# 4. 获取某一个轴上的数据最小值
print("axis 获取 score 数组中一行的最小值：")
result = np.min(score, axis=0)
print(result)
# 5. 数据的比较
print("np.argmax()获取 score 数组中每一行的最大值的索引：")
result = np.argmax(score, axis=1)
print(result)
result = np.maximum([-2, -1, 0, 1, 2], 0)  # 第一个参数中的每一个数与第二个参数比较返回大的
print(result)
result = np.minimum([-2, -1, 0, 1, 2], 0)  # 第一个参数中的每一个数与第二个参数比较返回小的
print(result)
result = np.maximum([-2, -1, 4, 1, 2], [1, 2, 3, 4, 5])
print(result)
# 接受的两个参数，也可以大小一致;第二个参数只是一个单独的值时，其实是用到了维度的广播机制；

[[80 88]
 [82 81]
 [75 81]]
np.max()获取 score 数组中的所有数据最大值：
88
axis 获取 score 数组中一列的最大值：
[88 82 81]
np.min()获取 score 数组中的所有数据最小值：
75
axis 获取 score 数组中一行的最小值：
[75 81]
np.argmax()获取 score 数组中每一行的最大值的索引：
[1 0 1]
[0 0 0 1 2]
[-2 -1  0  0  0]
[1 2 4 4 5]


In [ ]:
'''通用函数：
numpy.sqrt(array)	平方根函数
numpy.exp(array)	e^array[i]的数组
numpy.abs/fabs(array)	计算绝对值
numpy.square(array)	计算各元素的平方 等于array	2
numpy.log/log10/log2(array)	计算各元素的各种对数
numpy.sign(array)	计算各元素正负号
numpy.isnan(array)	计算各元素是否为NaN
numpy.isinf(array)	计算各元素是否为NaN
numpy.cos/cosh/sin/sinh/tan/tanh(array) 三角函数
numpy.modf(array)	将array中值得整数和小数分离，作两个数组返回
numpy.ceil(array)	向上取整,也就是取比这个数大的整数
numpy.floor(array)	向下取整,也就是取比这个数小的整数
numpy.rint(array)	四舍五入
numpy.trunc(array)	向0取整
numpy.cos(array)	正弦值
numpy.sin(array)	余弦值
numpy.tan(array)	正切值

numpy.add(array1,array2)	元素级加法
numpy.subtract(array1,array2)	元素级减法
numpy.multiply(array1,array2)	元素级乘法
numpy.divide(array1,array2)	元素级除法 array1./array2
numpy.power(array1,array2)	元素级指数 array1.^array2
numpy.maximum/minimum(array1,aray2) 元素级最大值
numpy.fmax/fmin(array1,array2)	元素级最大值，忽略NaN
numpy.mod(array1,array2)	元素级求模
numpy.copysign(array1,array2)	将第二个数组中值得符号复制给第一个数组中值
numpy.greater/greater_equal/less/less_equal/equal/not_equal (array1,array2)
元素级比较运算，产生布尔数组
numpy.logical_end/logical_or/logic_xor(array1,array2)元素级的真值逻辑运算
'''

In [233]:
# 6. 求平均值
result = np.mean(score)  # 获取所有数据的平均值
print(result)
result = np.mean(score, axis=0)  # 获取某一行或者某一列的平均值
print(result)

# 7. 求前缀和
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.cumsum(axis=0))
'''
[1, 2, 3]------>	|1	|2	|3	|
[4, 5, 6]------>	|5=1+4 |7=2+5 |9=3+6|
'''
print(arr.cumsum(axis=1))
'''
[1, 2, 3]------>	|1	|2+1	|3+2+1	|
[4, 5, 6]------>	|4	|4+5	|4+5+6	|
'''
# 拓展：方差var, 协方差cov, 计算平均值 average, 计算中位数 median

81.16666666666667
[79.         83.33333333]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]


'\n[1, 2, 3]------>\t|1\t|2+1\t|3+2+1\t|\n[4, 5, 6]------>\t|4\t|4+5\t|4+5+6\t|\n'

In [234]:
# 8. argmin求最小值索引
result = np.argmin(score, axis=0)
res = np.min(score, axis=0)  #这样我们就可以知道最小的81是第二排的，是从前往后遍历的
print(result, res)

# 9. 求每一列的标准差（这里是总体标准差）
# 标准差是一组数据平均值分散程度的一种度量。一个较大的标准差，代表大部分数值和其平均值之间差异较大；
# 一个较小的标准差，代表这些数据较接近平均值反应出数据的波动稳定情况，越大表示波动越大，越不稳定。
result = np.std(score, axis=0)
print(result)

# 10. 极 值
result = np.ptp(score, axis=None)  #就是最大值和最小值的差
print(result)

[2 1] [75 81]
[2.94392029 3.29983165]
13


In [235]:
t = np.arange(30).reshape(10, 3)
np.mean(t, axis=0)  # 计算每一列的平均值

array([13.5, 14.5, 15.5])