In [2]:
import pandas as pd

# Series

In [3]:
ser_obj = pd.Series(range(10, 20)) # 默认索引从0开始
print(ser_obj) #打印输出会带有类型

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64


In [4]:
# 获取数据
print(ser_obj.values)  #values实际是ndarray
print(type(ser_obj.values)) #类型是ndarray
# 获取索引
print(ser_obj.index)  #内部自带的类型--RangeIndex
ser_obj.dtype #数据类型

[10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
RangeIndex(start=0, stop=10, step=1)


dtype('int64')

In [5]:
print(ser_obj[0]) 
ser_obj[9] 
# 访问不存在的索引下标会报keyerror
# ser_obj[11]

10


np.int64(19)

In [6]:
print(ser_obj * 2)  #元素级乘法
print(ser_obj > 15) #返回一个bool序列

0    20
1    22
2    24
3    26
4    28
5    30
6    32
7    34
8    36
9    38
dtype: int64
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool


In [7]:
#字典变为series，索引是字典的key，value是字典的value，感受非默认索引
year_data = {2001: 17.8, 2005: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2)
print('-'*50)
print(ser_obj2.index)
print('-'*50)
print(ser_obj2[2001])
ser_obj2.values

2001    17.8
2005    20.1
2003    16.5
dtype: float64
--------------------------------------------------
Index([2001, 2005, 2003], dtype='int64')
--------------------------------------------------
17.8


array([17.8, 20.1, 16.5])

In [8]:
# 起名
print(ser_obj2.name) #Series名字
print(ser_obj2.index.name)  #索引名字
ser_obj2.name = 'temp'
ser_obj2.index.name = 'year1'
print('-'*50)
print(ser_obj2.head())  #head默认显示前5行

None
None
--------------------------------------------------
year1
2001    17.8
2005    20.1
2003    16.5
Name: temp, dtype: float64


# DataFrame

In [9]:
import numpy as np

# 通过ndarray构建DataFrame
t = pd.DataFrame(np.arange(12).reshape((3,4))) #默认索引是0-2
print(t)

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11


In [10]:
array = np.random.randn(6,4)
print(array)
print('-'*50)
df_obj = pd.DataFrame(array)
print(df_obj.head()) #默认显示前5行

[[ 0.22757718  1.30884738 -0.86276032  0.49541302]
 [ 0.80774042 -0.71193226  0.50349032 -1.44134527]
 [-1.51546631 -0.04649081  0.39671468  0.1138541 ]
 [-0.03428286  0.4172503   0.89117395  1.33407367]
 [-0.25141485  0.89032542  0.1087899  -1.81562907]
 [-0.38587169 -0.02228242  0.08171101  0.74655267]]
--------------------------------------------------
          0         1         2         3
0  0.227577  1.308847 -0.862760  0.495413
1  0.807740 -0.711932  0.503490 -1.441345
2 -1.515466 -0.046491  0.396715  0.113854
3 -0.034283  0.417250  0.891174  1.334074
4 -0.251415  0.890325  0.108790 -1.815629


In [11]:
print(t.loc[0]) #单独把某一行取出来,类型是series

0    0
1    1
2    2
3    3
Name: 0, dtype: int64


In [12]:
# 列表套字典  变df
d2 =[{"name" : "xiaohong" ,"age" :32,"tel" :10010},
     { "name": "xiaogang" ,"tel": 10000} ,
     {"name":"xiaowang" ,"age":22}]
df6=pd.DataFrame(d2)
print(df6) #缺失值会用NaN填充
print(type(df6.values)) #ndarray

       name   age      tel
0  xiaohong  32.0  10010.0
1  xiaogang   NaN  10000.0
2  xiaowang  22.0      NaN
<class 'numpy.ndarray'>


In [13]:
pd.Series(1, index=list(range(3,7)),dtype='float32') # 指定索引和数据类型

3    1.0
4    1.0
5    1.0
6    1.0
dtype: float32

In [14]:
#df中不同列可以是不同的数据类型,同一列必须是一个数据类型
import pandas as pd
import numpy as np
dict_data = {'A': 1,
             'B': pd.Timestamp('20190926'),
             'C': pd.Series(1, index=list(range(4)),dtype='float32'),
             'D': np.array([1,2,3,4],dtype='int32'),
             'E': ["Python","Java","C++","C"],
             'F': 'wangdao' }
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2)

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao


In [15]:
print(df_obj2.index) #行索引,重点
#补课改变
# df_obj2.index[0]=2  不可以单独修改某个索引值
print(df_obj2.columns) #列索引，重点
print(df_obj2.dtypes)# #每一列的数据类型，重点

Index([0, 1, 2, 3], dtype='int64')
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')
A            int64
B    datetime64[s]
C          float32
D            int32
E           object
F           object
dtype: object


In [16]:
# 感受日期,初始化df，设置行索引，列索引
dates = pd.date_range('20130101', periods=6) # 默认freq='D'，即天
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)
print('-'*50)
print(df.index)

                   A         B         C         D
2013-01-01  0.886387 -0.545379 -0.725058 -1.695820
2013-01-02 -3.482072  1.157349  0.032185  1.331485
2013-01-03  0.042335  0.548111  0.717093  0.930597
2013-01-04 -0.165636  1.030520  0.107688 -0.900077
2013-01-05 -0.566114  0.768251 -0.585203  0.374901
2013-01-06  0.947832 -0.085734 -1.444385 -0.025543
--------------------------------------------------
DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


In [17]:
#取数据
print(df_obj2)
print('-'*50)
print(type(df_obj2))
print('-'*50)
#pd中使用索引名来取某一行，或者列
print(df_obj2['B']) 
print('-'*50)
#把df的某一列取出来是series
print(type(df_obj2['B']))

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
--------------------------------------------------
0   2019-09-26
1   2019-09-26
2   2019-09-26
3   2019-09-26
Name: B, dtype: datetime64[s]
--------------------------------------------------
<class 'pandas.core.series.Series'>


In [18]:
#增加列数据，列名是自定义的
print(df_obj2.head())
df_obj2['G'] = df_obj2['D'] + 4
print('-'*50)
print(df_obj2.head())

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao
--------------------------------------------------
   A          B    C  D       E        F  G
0  1 2019-09-26  1.0  1  Python  wangdao  5
1  1 2019-09-26  1.0  2    Java  wangdao  6
2  1 2019-09-26  1.0  3     C++  wangdao  7
3  1 2019-09-26  1.0  4       C  wangdao  8


In [19]:
# 删除列
del(df_obj2['G']) # 删除第G列
print(df_obj2.head())

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao


# Series索引

In [20]:
# 整数索引
ser_obj = pd.Series(range(5), index = list("abcde"))
print(ser_obj)
ser_obj.index

a    0
b    1
c    2
d    3
e    4
dtype: int64


Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [21]:
# 行索引，不仅可以用索引名，可以用索引位置或来取
print(ser_obj['b']) #索引名
print(ser_obj[2]) #位置索引

1
2


C:\Users\klklklk\AppData\Local\Temp\ipykernel_25792\2834633063.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(ser_obj[2]) #位置索引


In [22]:
print(ser_obj.loc['b']) #索引名
print(ser_obj.iloc[2]) #位置索引

1
2


In [23]:
# 切片索引
print(ser_obj.iloc[1:3])  #索引位置取数据，左闭右开
print(ser_obj.loc['b':'d'])  #记住索引名  左闭右闭

b    1
c    2
dtype: int64
b    1
c    2
d    3
dtype: int64


In [24]:
# 不连续索引
print(ser_obj.iloc[[0, 2, 4]])
print(ser_obj.loc[['a', 'e']])

a    0
c    2
e    4
dtype: int64
a    0
e    4
dtype: int64


In [25]:
# 布尔索引
ser_bool = ser_obj > 2
print(ser_obj)
print(ser_bool)

a    0
b    1
c    2
d    3
e    4
dtype: int64
a    False
b    False
c    False
d     True
e     True
dtype: bool


In [26]:
print(ser_obj[ser_bool])
print(ser_obj[ser_obj > 2]) #取出大于2的元素

d    3
e    4
dtype: int64
d    3
e    4
dtype: int64


# DataFrame索引

In [27]:
import numpy as np
df_obj = pd.DataFrame(np.random.randn(5,4), columns = ['a', 'b', 'c', 'd'])
print(df_obj.head())

          a         b         c         d
0 -0.884740  0.773197  0.077357 -1.379102
1 -0.473878 -1.548291 -1.220131 -0.594918
2 -0.165541 -0.495790 -1.133684 -0.515676
3 -0.976644 -1.433375  1.600013 -2.141396
4  0.548477  0.213537 -0.371267  0.494508


In [28]:
# 列索引
print(df_obj['a']) # 返回Series类型
print('-'*50)
print(df_obj[['a']]) # 返回DataFrame类型，要加[]
print('-'*50)
print(type(df_obj[['a']])) # 返回DataFrame类型

0   -0.884740
1   -0.473878
2   -0.165541
3   -0.976644
4    0.548477
Name: a, dtype: float64
--------------------------------------------------
          a
0 -0.884740
1 -0.473878
2 -0.165541
3 -0.976644
4  0.548477
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>


In [29]:
# 标签索引 loc，建议使用loc，效率更高
# Series
ser_obj = pd.Series(range(5), index = list("abcde"))
print(ser_obj)
print(ser_obj['b':'d'])
print(ser_obj.loc['b':'d']) #前闭后闭

a    0
b    1
c    2
d    3
e    4
dtype: int64
b    1
c    2
d    3
dtype: int64
b    1
c    2
d    3
dtype: int64


In [30]:
# DataFrame
df_obj = pd.DataFrame(np.random.randn(5,4), columns = list('abcd'), index=list('abcde'))
print(df_obj)
print('-'*50)
print(df_obj['a'])  #建议不用,拿的是列
print('-'*50)
print(df_obj.loc['a'])  #拿的是行
print('-'*50)

          a         b         c         d
a -0.719168  0.976984 -0.861676  2.332541
b -0.520978 -0.270713 -0.171339 -0.241201
c -1.013495 -0.083344 -1.302325  0.012956
d  1.195310  1.701337 -0.923097  0.516300
e  0.131203 -0.205279  0.230157  1.026665
--------------------------------------------------
a   -0.719168
b   -0.520978
c   -1.013495
d    1.195310
e    0.131203
Name: a, dtype: float64
--------------------------------------------------
a   -0.719168
b    0.976984
c   -0.861676
d    2.332541
Name: a, dtype: float64
--------------------------------------------------


In [31]:
# 行和列组合：第一个参数索引行，第二个参数是列,loc或者iloc效率高于直接用取下标的方式，前闭后闭
print(df_obj.loc['a':'c', 'b':'d']) #连续索引
print(df_obj.loc[['a','c'], ['b','d']]) #不连续索引
print(df_obj.loc[['c'],['b']]) #取一个值,返回的是DataFrame类型
print(df_obj.loc['c','b'])  #取一个值

          b         c         d
a  0.976984 -0.861676  2.332541
b -0.270713 -0.171339 -0.241201
c -0.083344 -1.302325  0.012956
          b         d
a  0.976984  2.332541
c -0.083344  0.012956
          b
c -0.083344
-0.08334402837703468


# iloc 位置索引(推荐使用)

In [32]:
ser_obj
print('-'*50)
# Series
print(ser_obj[1:3])
print('-'*50)
print(ser_obj.iloc[1:3]) # 前闭后开[)，效率高

--------------------------------------------------
b    1
c    2
dtype: int64
--------------------------------------------------
b    1
c    2
dtype: int64


In [33]:
# DataFrame，iloc是前闭后开[)
print(df_obj)
print('-'*50)
print(df_obj.iloc[0:2, 0:2]) 
print('-'*50)
print(df_obj.iloc[[0,2], [0,2]]) # 不连续索引
print('-'*50)
print(df_obj.iloc[0,0]) # 取一个值

          a         b         c         d
a -0.719168  0.976984 -0.861676  2.332541
b -0.520978 -0.270713 -0.171339 -0.241201
c -1.013495 -0.083344 -1.302325  0.012956
d  1.195310  1.701337 -0.923097  0.516300
e  0.131203 -0.205279  0.230157  1.026665
--------------------------------------------------
          a         b
a -0.719168  0.976984
b -0.520978 -0.270713
--------------------------------------------------
          a         c
a -0.719168 -0.861676
c -1.013495 -1.302325
--------------------------------------------------
-0.7191683936530212


In [34]:
#没有设置行和列索引的DataFrame，iloc和loc的区别
df_obj2 = pd.DataFrame(np.random.randn(5,4))
print(df_obj2)
print('-'*50)
print(df_obj2.iloc[0:2]) #左闭右开 2行
print('-'*50)
print(df_obj2.loc[0:2]) #左闭右闭 3行

          0         1         2         3
0 -0.364571 -0.267140  0.698633  0.035545
1  3.239999  1.222401  0.889780  0.426143
2  1.769561 -0.284521 -0.713485 -2.015137
3  0.355720  1.448929  1.616658  0.821750
4 -1.723439  0.567111 -0.267007 -0.252076
--------------------------------------------------
          0         1         2         3
0 -0.364571 -0.267140  0.698633  0.035545
1  3.239999  1.222401  0.889780  0.426143
--------------------------------------------------
          0         1         2         3
0 -0.364571 -0.267140  0.698633  0.035545
1  3.239999  1.222401  0.889780  0.426143
2  1.769561 -0.284521 -0.713485 -2.015137


# 对齐运算

In [35]:
import pandas as pd
s1 = pd.Series(range(10, 20), index = range(10))
s2 = pd.Series(range(20, 25), index = range(5))
# Series 对齐运算
print('s1+s2: ')
s3=s1+s2
print(s3)  #缺失数据默认是NaN  np.nan

s1+s2: 
0    30.0
1    32.0
2    34.0
3    36.0
4    38.0
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
dtype: float64


In [36]:
#两个长度不同的一维ndarray相加
a1 = np.array([1,2,3,4,5])
a2 = np.array([1]) # 长度为1
print(a2.shape)
print(a1+a2)

(1,)
[2 3 4 5 6]


In [37]:
print(s1)
print(s2)
print(s3)
print(np.isnan(s3[6]))
print('-'*50)
# 总结：没对齐的元素，默认填充NaN，对齐运算时，fill_value参数可以指定填充值
print(s2.add(s1, fill_value = 0))  #未对齐的数据将和填充值做运算
print(s2.sub(s1, fill_value = 0)) 

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
0    20
1    21
2    22
3    23
4    24
dtype: int64
0    30.0
1    32.0
2    34.0
3    36.0
4    38.0
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
dtype: float64
True
--------------------------------------------------
0    30.0
1    32.0
2    34.0
3    36.0
4    38.0
5    15.0
6    16.0
7    17.0
8    18.0
9    19.0
dtype: float64
0    10.0
1    10.0
2    10.0
3    10.0
4    10.0
5   -15.0
6   -16.0
7   -17.0
8   -18.0
9   -19.0
dtype: float64


In [38]:
#df的对齐运算
import numpy as np
df1 = pd.DataFrame(np.ones((2,2)), columns = ['a', 'b'])
df2 = pd.DataFrame(np.ones((3,3)), columns = ['a', 'b', 'c'])
print(df1)
print(df2)
print('-'*50)
print(df2.dtypes)
# 总结：没对齐的元素，默认填充NaN，对齐运算时，fill_value参数可以指定填充值
print(df1-df2)
print(df2.sub(df1, fill_value = 2)) #未对齐的数据将和填充值做运算,df1的nan填充为2

     a    b
0  1.0  1.0
1  1.0  1.0
     a    b    c
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0
--------------------------------------------------
a    float64
b    float64
c    float64
dtype: object
     a    b   c
0  0.0  0.0 NaN
1  0.0  0.0 NaN
2  NaN  NaN NaN
     a    b    c
0  0.0  0.0 -1.0
1  0.0  0.0 -1.0
2 -1.0 -1.0 -1.0
