In [120]:
import pandas as pd

# Series

In [121]:
ser_obj = pd.Series(range(10, 20)) # 默认索引从0开始
print(ser_obj) #打印输出会带有类型

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64


In [122]:
# 获取数据
print(ser_obj.values)  #values实际是ndarray
print(type(ser_obj.values)) #类型是ndarray
# 获取索引
print(ser_obj.index)  #内部自带的类型--RangeIndex
ser_obj.dtype #数据类型

[10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
RangeIndex(start=0, stop=10, step=1)


dtype('int64')

In [123]:
print(ser_obj[0]) 
ser_obj[9] 
# 访问不存在的索引下标会报keyerror
# ser_obj[11]

10


np.int64(19)

In [124]:
print(ser_obj * 2)  #元素级乘法
print(ser_obj > 15) #返回一个bool序列

0    20
1    22
2    24
3    26
4    28
5    30
6    32
7    34
8    36
9    38
dtype: int64
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool


In [125]:
#字典变为series，索引是字典的key，value是字典的value，感受非默认索引
year_data = {2001: 17.8, 2005: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2)
print('-'*50)
print(ser_obj2.index)
print('-'*50)
print(ser_obj2[2001])
ser_obj2.values

2001    17.8
2005    20.1
2003    16.5
dtype: float64
--------------------------------------------------
Index([2001, 2005, 2003], dtype='int64')
--------------------------------------------------
17.8


array([17.8, 20.1, 16.5])

In [126]:
# 起名
print(ser_obj2.name) #Series名字
print(ser_obj2.index.name)  #索引名字
ser_obj2.name = 'temp'
ser_obj2.index.name = 'year1'
print('-'*50)
print(ser_obj2.head())  #head默认显示前5行

None
None
--------------------------------------------------
year1
2001    17.8
2005    20.1
2003    16.5
Name: temp, dtype: float64


# DataFrame

In [127]:
import numpy as np

# 通过ndarray构建DataFrame
t = pd.DataFrame(np.arange(12).reshape((3,4))) #默认索引是0-2
print(t)

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11


In [128]:
array = np.random.randn(6,4)
print(array)
print('-'*50)
df_obj = pd.DataFrame(array)
print(df_obj.head()) #默认显示前5行

[[-0.50269408 -2.37356318  0.03596151 -1.01000337]
 [ 0.96619052 -1.33521247  0.19687893  0.18764603]
 [-0.70036044  0.56887015  2.20710332  0.50933945]
 [-0.17445637 -0.83778765  0.27920292 -0.3297641 ]
 [-0.94857004 -0.35065724  1.68263947 -0.73301858]
 [ 1.81224046 -0.30405224  2.03605305 -0.09237553]]
--------------------------------------------------
          0         1         2         3
0 -0.502694 -2.373563  0.035962 -1.010003
1  0.966191 -1.335212  0.196879  0.187646
2 -0.700360  0.568870  2.207103  0.509339
3 -0.174456 -0.837788  0.279203 -0.329764
4 -0.948570 -0.350657  1.682639 -0.733019


In [129]:
print(t.loc[0]) #单独把某一行取出来,类型是series

0    0
1    1
2    2
3    3
Name: 0, dtype: int64


In [130]:
# 列表套字典  变df
d2 =[{"name" : "xiaohong" ,"age" :32,"tel" :10010},
     { "name": "xiaogang" ,"tel": 10000} ,
     {"name":"xiaowang" ,"age":22}]
df6=pd.DataFrame(d2)
print(df6) #缺失值会用NaN填充
print(type(df6.values)) #ndarray

       name   age      tel
0  xiaohong  32.0  10010.0
1  xiaogang   NaN  10000.0
2  xiaowang  22.0      NaN
<class 'numpy.ndarray'>


In [131]:
pd.Series(1, index=list(range(3,7)),dtype='float32') # 指定索引和数据类型

3    1.0
4    1.0
5    1.0
6    1.0
dtype: float32

In [132]:
#df中不同列可以是不同的数据类型,同一列必须是一个数据类型
import pandas as pd
import numpy as np
dict_data = {'A': 1,
             'B': pd.Timestamp('20190926'),
             'C': pd.Series(1, index=list(range(4)),dtype='float32'),
             'D': np.array([1,2,3,4],dtype='int32'),
             'E': ["Python","Java","C++","C"],
             'F': 'wangdao' }
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2)

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao


In [133]:
print(df_obj2.index) #行索引,重点
#补课改变
# df_obj2.index[0]=2  不可以单独修改某个索引值
print(df_obj2.columns) #列索引，重点
print(df_obj2.dtypes)# #每一列的数据类型，重点

Index([0, 1, 2, 3], dtype='int64')
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')
A            int64
B    datetime64[s]
C          float32
D            int32
E           object
F           object
dtype: object


In [134]:
# 感受日期,初始化df，设置行索引，列索引
dates = pd.date_range('20130101', periods=6) # 默认freq='D'，即天
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)
print('-'*50)
print(df.index)

                   A         B         C         D
2013-01-01 -2.257820 -0.179333  0.743828  0.455928
2013-01-02 -0.902762  0.786539 -1.129720 -0.366549
2013-01-03  0.589990  1.339084  1.545517 -1.881384
2013-01-04 -0.525825 -0.175177  1.847385 -0.771559
2013-01-05  2.301837  1.776843 -0.829074  1.037095
2013-01-06  0.655232  0.655322 -0.623508  0.854639
--------------------------------------------------
DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


In [135]:
#取数据
print(df_obj2)
print('-'*50)
print(type(df_obj2))
print('-'*50)
#pd中使用索引名来取某一行，或者列
print(df_obj2['B']) 
print('-'*50)
#把df的某一列取出来是series
print(type(df_obj2['B']))

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
--------------------------------------------------
0   2019-09-26
1   2019-09-26
2   2019-09-26
3   2019-09-26
Name: B, dtype: datetime64[s]
--------------------------------------------------
<class 'pandas.core.series.Series'>


In [136]:
#增加列数据，列名是自定义的
print(df_obj2.head())
df_obj2['G'] = df_obj2['D'] + 4
print('-'*50)
print(df_obj2.head())

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao
--------------------------------------------------
   A          B    C  D       E        F  G
0  1 2019-09-26  1.0  1  Python  wangdao  5
1  1 2019-09-26  1.0  2    Java  wangdao  6
2  1 2019-09-26  1.0  3     C++  wangdao  7
3  1 2019-09-26  1.0  4       C  wangdao  8


In [137]:
# 删除列
del(df_obj2['G']) # 删除第G列
print(df_obj2.head())

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao


# Series索引

In [138]:
# 整数索引
ser_obj = pd.Series(range(5), index = list("abcde"))
print(ser_obj)
ser_obj.index

a    0
b    1
c    2
d    3
e    4
dtype: int64


Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [139]:
# 行索引，不仅可以用索引名，可以用索引位置或来取
print(ser_obj['b']) #索引名
print(ser_obj[2]) #位置索引

1
2


C:\Users\klklklk\AppData\Local\Temp\ipykernel_21204\2834633063.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(ser_obj[2]) #位置索引


In [140]:
print(ser_obj.loc['b']) #索引名
print(ser_obj.iloc[2]) #位置索引

1
2


In [141]:
# 切片索引
print(ser_obj.iloc[1:3])  #索引位置取数据，左闭右开
print(ser_obj.loc['b':'d'])  #记住索引名  左闭右闭

b    1
c    2
dtype: int64
b    1
c    2
d    3
dtype: int64


In [142]:
# 不连续索引
print(ser_obj.iloc[[0, 2, 4]])
print(ser_obj.loc[['a', 'e']])

a    0
c    2
e    4
dtype: int64
a    0
e    4
dtype: int64


In [143]:
# 布尔索引
ser_bool = ser_obj > 2
print(ser_obj)
print(ser_bool)

a    0
b    1
c    2
d    3
e    4
dtype: int64
a    False
b    False
c    False
d     True
e     True
dtype: bool


In [144]:
print(ser_obj[ser_bool])
print(ser_obj[ser_obj > 2]) #取出大于2的元素

d    3
e    4
dtype: int64
d    3
e    4
dtype: int64


# DataFrame索引

In [145]:
import numpy as np
df_obj = pd.DataFrame(np.random.randn(5,4), columns = ['a', 'b', 'c', 'd'])
print(df_obj.head())

          a         b         c         d
0 -2.628491  0.926109 -1.076463  0.553783
1  1.634567  0.961602  0.277668  1.842283
2  0.016048 -0.165606  0.622628 -0.149792
3  0.693636  2.226512 -1.096077 -0.244484
4 -0.053381  0.220395  0.728236 -0.633440


In [146]:
# 列索引
print(df_obj['a']) # 返回Series类型
print('-'*50)
print(df_obj[['a']]) # 返回DataFrame类型，要加[]
print('-'*50)
print(type(df_obj[['a']])) # 返回DataFrame类型

0   -2.628491
1    1.634567
2    0.016048
3    0.693636
4   -0.053381
Name: a, dtype: float64
--------------------------------------------------
          a
0 -2.628491
1  1.634567
2  0.016048
3  0.693636
4 -0.053381
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>


In [147]:
# 标签索引 loc，建议使用loc，效率更高
# Series
ser_obj = pd.Series(range(5), index = list("abcde"))
print(ser_obj)
print(ser_obj['b':'d'])
print(ser_obj.loc['b':'d']) #前闭后闭

a    0
b    1
c    2
d    3
e    4
dtype: int64
b    1
c    2
d    3
dtype: int64
b    1
c    2
d    3
dtype: int64


In [148]:
# DataFrame
df_obj = pd.DataFrame(np.random.randn(5,4), columns = list('abcd'), index=list('abcde'))
print(df_obj)
print('-'*50)
print(df_obj['a'])  #建议不用,拿的是列
print('-'*50)
print(df_obj.loc['a'])  #拿的是行
print('-'*50)

          a         b         c         d
a -0.574157 -1.580237 -0.680712  1.998322
b -1.559254 -0.922736 -1.013691  1.270840
c -0.014716 -0.316997 -0.110408  1.232087
d  0.635650  1.201598  0.337649  1.044320
e -0.182622  1.113727  1.112394 -0.713335
--------------------------------------------------
a   -0.574157
b   -1.559254
c   -0.014716
d    0.635650
e   -0.182622
Name: a, dtype: float64
--------------------------------------------------
a   -0.574157
b   -1.580237
c   -0.680712
d    1.998322
Name: a, dtype: float64
--------------------------------------------------


In [149]:
# 行和列组合：第一个参数索引行，第二个参数是列,loc或者iloc效率高于直接用取下标的方式，前闭后闭
print(df_obj.loc['a':'c', 'b':'d']) #连续索引
print(df_obj.loc[['a','c'], ['b','d']]) #不连续索引
print(df_obj.loc[['c'],['b']]) #取一个值,返回的是DataFrame类型
print(df_obj.loc['c','b'])  #取一个值

          b         c         d
a -1.580237 -0.680712  1.998322
b -0.922736 -1.013691  1.270840
c -0.316997 -0.110408  1.232087
          b         d
a -1.580237  1.998322
c -0.316997  1.232087
          b
c -0.316997
-0.316996689761424


# iloc 位置索引(推荐使用)

In [150]:
ser_obj
print('-'*50)
# Series
print(ser_obj[1:3])
print('-'*50)
print(ser_obj.iloc[1:3]) # 前闭后开[)，效率高

--------------------------------------------------
b    1
c    2
dtype: int64
--------------------------------------------------
b    1
c    2
dtype: int64


In [151]:
# DataFrame，iloc是前闭后开[)
print(df_obj)
print('-'*50)
print(df_obj.iloc[0:2, 0:2]) 
print('-'*50)
print(df_obj.iloc[[0,2], [0,2]]) # 不连续索引
print('-'*50)
print(df_obj.iloc[0,0]) # 取一个值

          a         b         c         d
a -0.574157 -1.580237 -0.680712  1.998322
b -1.559254 -0.922736 -1.013691  1.270840
c -0.014716 -0.316997 -0.110408  1.232087
d  0.635650  1.201598  0.337649  1.044320
e -0.182622  1.113727  1.112394 -0.713335
--------------------------------------------------
          a         b
a -0.574157 -1.580237
b -1.559254 -0.922736
--------------------------------------------------
          a         c
a -0.574157 -0.680712
c -0.014716 -0.110408
--------------------------------------------------
-0.5741573235551602


In [152]:
#没有设置行和列索引的DataFrame，iloc和loc的区别
df_obj2 = pd.DataFrame(np.random.randn(5,4))
print(df_obj2)
print('-'*50)
print(df_obj2.iloc[0:2]) #左闭右开 2行
print('-'*50)
print(df_obj2.loc[0:2]) #左闭右闭 3行

          0         1         2         3
0 -1.431449 -1.941465  1.197764  0.017669
1 -0.543166 -1.048374  0.346701 -0.106337
2 -1.299320 -1.651850 -0.090492 -0.076333
3  0.606296  1.363607 -1.108068 -0.833381
4 -1.593904  0.138387  1.176106  0.532581
--------------------------------------------------
          0         1         2         3
0 -1.431449 -1.941465  1.197764  0.017669
1 -0.543166 -1.048374  0.346701 -0.106337
--------------------------------------------------
          0         1         2         3
0 -1.431449 -1.941465  1.197764  0.017669
1 -0.543166 -1.048374  0.346701 -0.106337
2 -1.299320 -1.651850 -0.090492 -0.076333


# 对齐运算

In [153]:
import pandas as pd
s1 = pd.Series(range(10, 20), index = range(10))
s2 = pd.Series(range(20, 25), index = range(5))
# Series 对齐运算
print('s1+s2: ')
s3=s1+s2
print(s3)  #缺失数据默认是NaN  np.nan

s1+s2: 
0    30.0
1    32.0
2    34.0
3    36.0
4    38.0
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
dtype: float64


In [154]:
#两个长度不同的一维ndarray相加
a1 = np.array([1,2,3,4,5])
a2 = np.array([1]) # 长度为1
print(a2.shape)
print(a1+a2)

(1,)
[2 3 4 5 6]


In [155]:
print(s1)
print(s2)
print(s3)
print(np.isnan(s3[6]))
print('-'*50)
# 总结：没对齐的元素，默认填充NaN，对齐运算时，fill_value参数可以指定填充值
print(s2.add(s1, fill_value = 0))  #未对齐的数据将和填充值做运算
print(s2.sub(s1, fill_value = 0)) 

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
0    20
1    21
2    22
3    23
4    24
dtype: int64
0    30.0
1    32.0
2    34.0
3    36.0
4    38.0
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
dtype: float64
True
--------------------------------------------------
0    30.0
1    32.0
2    34.0
3    36.0
4    38.0
5    15.0
6    16.0
7    17.0
8    18.0
9    19.0
dtype: float64
0    10.0
1    10.0
2    10.0
3    10.0
4    10.0
5   -15.0
6   -16.0
7   -17.0
8   -18.0
9   -19.0
dtype: float64


In [156]:
#df的对齐运算
import numpy as np
df1 = pd.DataFrame(np.ones((2,2)), columns = ['a', 'b'])
df2 = pd.DataFrame(np.ones((3,3)), columns = ['a', 'b', 'c'])
print(df1)
print(df2)
print('-'*50)
print(df2.dtypes)
# 总结：没对齐的元素，默认填充NaN，对齐运算时，fill_value参数可以指定填充值
print(df1-df2)
print(df2.sub(df1, fill_value = 2)) #未对齐的数据将和填充值做运算

     a    b
0  1.0  1.0
1  1.0  1.0
     a    b    c
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0
--------------------------------------------------
a    float64
b    float64
c    float64
dtype: object
     a    b   c
0  0.0  0.0 NaN
1  0.0  0.0 NaN
2  NaN  NaN NaN
     a    b    c
0  0.0  0.0 -1.0
1  0.0  0.0 -1.0
2 -1.0 -1.0 -1.0
